sudo: required

services:
  - docker

env:
  matrix:
    - CI_ROS_DISTRO="indigo"
    - CI_ROS_DISTRO="kinetic"
    - CI_ROS_DISTRO="lunar"
    - CI_ROS_DISTRO="melodic"

install:
  - docker build -t rospy_message_converter_$CI_ROS_DISTRO -f Dockerfile-$CI_ROS_DISTRO .

script:
  - docker run rospy_message_converter_$CI_ROS_DISTRO /bin/bash -c "source devel/setup.bash && CTEST_OUTPUT_ON_FAILURE=1 catkin_make test"
